# Fichier de configuration TastyCrousteam 
# contient les paramètres et les variables utilisés dans le programme

#agent 
nom d'équipe : TastyCrousteam

#coordonnées 
x : 0
y : 1
z : 2

path_lookahead : 3

#AgentCenter
# distance à partir de laquelle on considère notre distance par rapport au centre trop élevée
dist : 0.673833673012193

# à quel point on ajuste la direction
ajust : 0.6386812473361506


#AgentSpeed
# seuil à partir duquel on considère l'écart entre le front du kart et la direction du segment
ecartpetit : 3.1052264371860465
ecartgrand : 3.3379507231468204

# seuil à partir duquel on considère que la capacité à tourner le volant selon la vitesse(max_steer_angle)
max_steer_angle_petit : 0.25695886258961403
max_steer_angle_grand : 0.9824233440624094

#vitesse max ligne droite
accel_ligne_droite : 3.2936037808932275

#ralentissement dans un virage serré
frein_virage : 0.13929755500933277

#acceleration sortie de virage
accel_virage : 0.7532895208471412

#distance a partir de laquelle on reagit a un segment
dist_segment : 7.6537214237813975




#items bonus
bonus:
    - 0
    - 2
    - 3

#obstacles
obstacles:
    - 1
    - 4

#acceleration
base : 0.7
min : 0.1
max : 0.9

#boost
small : 0.2
big : 0.3



#AgentRescue
min_progress_threshold : 0.5
block_counter_threshold : 18
unblock_steps_default : 6


#AgentDrift
speed_threshold: 7.0
steer_threshold: 0.4 
stop_drift_speed: 4.0 
#max_steer_angle_petit et frein_virage dans AgentSpeed

