# Configuration The Winners
main_agent:
  path_lookahead : 2
  seuil_lenpoints : 2
  epsilon : 0.05
  seuil_road_straight: 0.8
  seuil_distance_stuck : 3
  seuil_distance : 2
  default_gain : 7.0

speed:
  vitesse_seuil : 20.0
  seuil_decalage_max : 10
  seuil_decalage_mid : 8
  seuil_decalage_low : 6
  seuil_decalage_min : 5
  acceleration_max : 1.0
  acceleration_mid : 0.55
  acceleration_low : 0.3
  acceleration_czero : 0.05
  acceleration_drift : 0.6

steering:
  empattement : 2.5

powerup:
  radar_xball : 0.8
  radar_xswatter : 0.4
  radar_zmin_ball : 2.0
  radar_zmin_swatter : 2.0
  radar_zmax_ball : 25.0
  radar_zmax_swatter : 5.0
  gain_steer : 7.0
  steer_allow_zipper : 0.4
  rate_steer : 0.8
  rate_target : 0.2

drift:
  timer_basic : 0
  cooldown_basic : 0
  timer_start : 15
  cooldown_start : 15
  coefficient_steer : 0.6
  speed_seuil : 12
  x_seuil : 3.0
  steer_seuil : 0.5

banana:
  dodge_timer_basic : 0
  dodge_timer_start : 10
  decalage_lateral : 3.0
  radar_x : 2.0
  radar_zmin : 0.0
  radar_zmax : 17.0
  seuil_ligne : 2.0
  default_gain : 7.0
  adjusted_gain : 6.0
  seuil_limite_path : 1.5

rescue:
  recovery_timer : 10
  seuil_agent_position : 20
  seuil_distance : 10.0
  seuil_delta : 3
  seuil_speed : 0.30
  seuil_blocked : 14
  seuil_blocked_trigger : 7

opponent:
  radar_x : 0.8
  radar_zmin : 0.1
  radar_zmax : 1.3
  decalage_lateral : 2.0
  default_gain : 7.0

nitro:
  seuil_energy : 0.5
  seuil_steer : 0.45
  seuil_target_now : 5
  seuil_target_soon : 5
  seuil_target_late : 7